### ISSUE TITLE
Diminuir tamanho das imagens da seção 'Time' para melhor a usabilidade em telas menores

### ISSUE THREAD

**Issue by diegobfernandez** [nepente/nepente.github.io#7]

**Comment by andrepoleza** [comment]
Que título enorme pra uma issue! :worried:

**Comment by andrepoleza** [comment]
Aproveitando a issue: o ideal era dar um espaçamento maior entre a foto, o nome e os ícones das redes sociais de cada um. O formato de hoje parece muito apertado.
